In [137]:
import numpy as np
import CcaGrid

In [138]:
NEIGHBORHOOD_MOORE = 0
NEIGHBORHOOD_NEUMANN = 1

num_columns = 10
num_rows = 10
num_states = 3
neighborhood_range = 1
neighboorhood_type = NEIGHBORHOOD_MOORE

### Helper functions

In [139]:
def wrap(x): 
    return (x[0] % 10, x[1] % 10)

### Create states

create array of 100 states

In [140]:
def randomStates(rows, columns, states):
    grid = np.random.rand(num_rows*num_columns) * (states-1)
    grid = grid.round()
    return grid

In [141]:
grid = randomStates(num_rows, num_columns, num_states)

In [142]:
grid

array([0., 2., 0., 0., 2., 1., 1., 1., 1., 1., 1., 2., 2., 0., 1., 2., 0.,
       1., 1., 2., 1., 1., 1., 1., 0., 1., 1., 2., 0., 2., 2., 1., 2., 1.,
       0., 1., 1., 1., 1., 0., 2., 2., 1., 2., 0., 2., 1., 1., 1., 2., 0.,
       2., 1., 0., 0., 1., 0., 1., 1., 1., 0., 2., 1., 0., 1., 1., 2., 1.,
       0., 1., 1., 1., 2., 1., 0., 1., 1., 1., 1., 2., 1., 0., 2., 1., 2.,
       1., 0., 0., 0., 1., 0., 1., 2., 1., 0., 0., 1., 1., 0., 1.])

### Create positions

In [143]:
def positions(rows, columns):
    return np.asarray(list(range(0, num_rows*num_columns)))

In [144]:
positions = positions(num_rows, num_columns)

In [145]:
positions

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

### Get position from coordinate

In [146]:
def position(coordinate, total_cols):
    return (coordinate[0]*total_cols) + coordinate[1]

### Create Moore neighborhood

** For cell (5, 5) **

In [147]:
current_row = 5
current_column = 5

In [153]:
def wrap_coordinate(coordinate, num_rows, num_columns):
    return (coordinate[0] % num_rows, coordinate[1] % num_columns)

In [156]:
def moore_neighborhood_positions(row, column, size, num_rows, num_columns):
    coordinates = []
    for row_offset in range(-size, size+1):
        for column_offset in range(-size, size+1):
            if (row_offset != 0) | (column_offset != 0):
                coordinates.append((row+row_offset, column+column_offset))
            
    return list(position(wrap_coordinate(x, num_rows, num_columns), num_columns) for x in coordinates)

In [161]:
neighborhood_positions = moore_neighborhood_positions(current_row, current_column, 1, num_rows, num_columns)

### Create neighborhood mask

In [166]:
def neighborhood_mask(neighborhood_positions, positions):
    return np.asarray(list(x not in neighbor_positions for x in positions))

In [167]:
neighbor_grid = neighborhood_mask(neighborhood_positions, positions)

In [168]:
np.asarray(neighbor_grid).reshape(10, 10)

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True, False, False, False,  True,  True,
         True],
       [ True,  True,  True,  True, False,  True, False,  True,  True,
         True],
       [ True,  True,  True,  True, False, False, False,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

### Use mask to query neighborhood

In [170]:
neighbor_states = np.ma.masked_array(grid, neighbor_grid)

In [174]:
neighbor_states

masked_array(data=[--, --, --, --, --, --, --, --, --, --, --, --, --, --,
                   --, --, --, --, --, --, --, --, --, --, --, --, --, --,
                   --, --, --, --, --, --, --, --, --, --, --, --, --, --,
                   --, --, 0.0, 2.0, 1.0, --, --, --, --, --, --, --, 0.0,
                   --, 0.0, --, --, --, --, --, --, --, 1.0, 1.0, 2.0, --,
                   --, --, --, --, --, --, --, --, --, --, --, --, --, --,
                   --, --, --, --, --, --, --, --, --, --, --, --, --, --,
                   --, --, --, --],
             mask=[ True,  True,  True,  True,  True,  True,  True,  True,
                    True,  True,  True,  True,  True,  True,  True,  True,
                    True,  True,  True,  True,  True,  True,  True,  True,
                    True,  True,  True,  True,  True,  True,  True,  True,
                    True,  True,  True,  True,  True,  True,  True,  True,
                    True,  True,  True,  True, False, False, Fal

In [176]:
neighbor_states.compressed()

array([0., 2., 1., 0., 0., 1., 1., 2.])

In [188]:
(neighbor_states.compressed() == 1).sum()

3

In [189]:
(neighbor_states.compressed() == 2).sum()

2

### Next steps
* Work with (views on) matrices
* Only work in 1 dimension until it is time to visualize the grid